//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOPATHManageConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOPATHManageConsole.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path discovered.  Added as &apos;default&apos;.
        /// </summary>
        internal static string GPTH_default_path_add_msg {
            get {
                return ResourceManager.GetString("GPTH_default_path_add_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string GPTH_default_path_key {
            get {
                return ResourceManager.GetString("GPTH_default_path_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of arguments.
        /// </summary>
        internal static string GPTH_invalid_num_args {
            get {
                return ResourceManager.GetString("GPTH_invalid_num_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key update failed.
        /// </summary>
        internal static string GPTH_key_update_fail_msg {
            get {
                return ResourceManager.GetString("GPTH_key_update_fail_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Updated.
        /// </summary>
        internal static string GPTH_key_updated {
            get {
                return ResourceManager.GetString("GPTH_key_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Paths currently set.
        /// </summary>
        internal static string GPTH_no_path_set {
            get {
                return ResourceManager.GetString("GPTH_no_path_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Go path does not appear to be set.
        /// </summary>
        internal static string GPTH_NoPath_ErrorMsg {
            get {
                return ResourceManager.GetString("GPTH_NoPath_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go does not appear to be installed.
        /// </summary>
        internal static string GPTH_NoRoot_ErrorMsg {
            get {
                return ResourceManager.GetString("GPTH_NoRoot_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path successfully added.
        /// </summary>
        internal static string GPTH_path_add {
            get {
                return ResourceManager.GetString("GPTH_path_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path add failed: .
        /// </summary>
        internal static string GPTH_path_add_failed {
            get {
                return ResourceManager.GetString("GPTH_path_add_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Removed.
        /// </summary>
        internal static string GPTH_path_removed {
            get {
                return ResourceManager.GetString("GPTH_path_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating path for key.
        /// </summary>
        internal static string GPTH_path_update {
            get {
                return ResourceManager.GetString("GPTH_path_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECTORY.
        /// </summary>
        internal static string GPTH_pathlist_header_DIR {
            get {
                return ResourceManager.GetString("GPTH_pathlist_header_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY.
        /// </summary>
        internal static string GPTH_pathlist_header_KEY {
            get {
                return ResourceManager.GetString("GPTH_pathlist_header_KEY", resourceCulture);
            }
        }
    }
}
